### ISSUE TITLE
Readme has wrong startup command

### ISSUE THREAD

**Issue by mmclachlan** [passport/express-4.x-twitter-example#8]
This is a pretty quick and easy fix, but instead of documenting this in the readme...
`CONSUMER_KEY=__TWITTER_CONSUMER_KEY__ CONSUMER_SECRET=__TWITTER_CONSUMER_SECRET__ node server.js`

it should be this...
`TWITTER_CONSUMER_KEY=__TWITTER_CONSUMER_KEY__ TWITTER_CONSUMER_SECRET=__TWITTER_CONSUMER_SECRET__ node server.js`

If not, you'll get this error on startup because it isn't looking up CONSUMER_KEY, it's looking up TWITTER_CONSUMER_KEY;
TypeError: OAuthStrategy requires a consumerKey option

**Comment by jaredhanson** [comment]
Fixed.
